version: '3'
services:
  hajusput-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassw0rd
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    expose:
      - 1433
    networks:
      - hajusput
    
  hajusput-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: hajusput-rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    networks:
      - hajusput
      
  rabbitmq-subscriber:
    restart: on-failure
    build:
      context: ./hajUsput.Subscriber
    environment:
      - RABBITMQ_HOST=hajusput-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_EMAIL=haj.usput@gmail.com
      - SMTP_PASSWORD="grwc uivn hgtn azyx"
    depends_on:
      - hajusput-sql
      - hajusput-api
      - hajusput-rabbitmq
    networks:
      - hajusput
      
  hajusput-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=hajusput-sql,1433;Database=180072;User=sa;Password=YourStrongPassw0rd;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=hajusput-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetcore-dev.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
    ports:
      - 7089:7089
    networks:
      - hajusput
    links:
      - hajusput-sql
    depends_on:
      - hajusput-sql
      - hajusput-rabbitmq

networks:
  hajusput:
    driver: bridge 